version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
      # - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./etc/nginx/mime.types:/etc/nginx/mime.types
    depends_on:
      - oj-app
    environment:
      - TZ=Asia/Seoul
    networks:
      - oj-network

    restart: always

  oj-app:
    build:
      context: .
    container_name: oj-app
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    command: npm start
    networks:
      - oj-network
networks:
  oj-network:
    name: nginx
    driver: bridge
